### ISSUE TITLE
error Cannot find the remote origin url

### ISSUE THREAD

**Issue by ionelmc** [IonicaBizau/git-stats-importer#1]
Seems it doesn't work on my git-svn repo :disappointed: 
```
$ git-stats-importer
error Cannot find the remote origin url. Please add it.
```

**Comment by IonicaBizau** [comment]
What's the output of `git config --get remote.origin.url`?

**Comment by ionelmc** [comment]
On Mon, Feb 9, 2015 at 6:11 PM, Ionică Bizău <notifications@github.com>
wrote:

> git config --get remote.origin.url


​No output at all. I don't have any remotes as you cannot push with a
git-svn repo.​



Thanks,
-- Ionel Cristian Mărieș, blog.ionelmc.ro

**Comment by IonicaBizau** [comment]
OK, so you have to add one. What do you mean by `git-svn`? Is it a `git + svn` repo? What is the remote url (where do you push the code)?

`git-stats` uses the remote urls to make differences between repositories.

**Comment by ionelmc** [comment]
This is git-svn: http://git-scm.com/docs/git-svn




Thanks,
-- Ionel Cristian Mărieș, blog.ionelmc.ro

**Comment by ionelmc** [comment]
I have this tho:

```
$ git svn info
Path: .
URL: https://some.url.example.com/to/svn/repo/trunk
Repository Root: https://some.url.example.com/to/svn/repo
Repository UUID: a0b528ad-c7e9-41a2-9749-cad4148cc57a
Revision: 12341234
Node Kind: directory
Schedule: normal
Last Changed Author: maries
Last Changed Rev: 12341234
Last Changed Date: 2015-02-09 15:58:31 +0200 (Mon, 09 Feb 2015)
```

Regardless, relying on remote urls seems unnecessary, commits already have a good id: the hash - why can't you compare just on that?

**Comment by IonicaBizau** [comment]
Is there a way to get the the url only?

In the future I will probably make some stats regarding the repositories too. 

In the meantime you can add a dummy remote url:

```sh
git remote add origin git@dummy.com:dummy/dummy.git
```

**Comment by philadams** [comment]
Aha! `git config --get remote.origin.url` assumes, of course, that your default remote is named `origin`. Because I often have multiple remotes on different servers, my 'default' GitHub remote is usually named `github`.

Perhaps git-stats-importer can use something like `git config --get remote.`git remote | head -n1`.url` instead?

**Comment by IonicaBizau** [comment]
@philadams :+1: Can you create a pull request with this? Also, would it solve the issue with `git-svn`?

**Comment by nilleb** [comment]
I reproduce this bug on windows, on a pure git (pure, not bare) repository.

>"Jenkins Integration\node_modules\.bin\git-stats-importer"
error Cannot find the remote origin url. Please add it.

>git config --get remote.origin.url
http://:@cgdlyovm0161:8080/tfs/tahaa/DT_FWK_GIT/_git/green

>git config --get remote.$(git remote | head -n1).url
error: invalid key: remote.$(git
head: 1).url: number of lines is so large that it is not representable

**Comment by IonicaBizau** [comment]
Hmm... interesting.

What about the following?

```sh
$ git config --get remote.`git remote | head -n1`.url
```

**Comment by nilleb** [comment]
Same error message

    error: invalid key: remote.`git
    head: 1`.url: number of lines is so large that it is not representable

**Comment by IonicaBizau** [comment]
@nilleb What about `git remote | head -n1`? Maybe I will separate them in two exec calls.

**Comment by philadams** [comment]
@IonicaBizau Yes - but I see you beat me to it! :+1:

I confirm it's working just fine as importing in my repos now - thank you!

**Comment by nilleb** [comment]
splitting the instruction in two distinct instructions works.
but, pay attention to the part `head -n1`: the remotes are sorted alphabetically, not by their degree of importance (all the remotes are equal in importance).
in my case, the first remote doesn't correspond to the default one.

**Comment by IonicaBizau** [comment]
How should do we define *the default remote*?

**Comment by mrzepinski** [comment]
+1

**Comment by philadams** [comment]
@nilleb @IonicaBizau I hadn't considered that. What exactly is the remote being used for? Just the `remote.whatever.url` as a key for the local commits cache? If so, I guess any remote regardless of importance would be fine?

**Comment by IonicaBizau** [comment]
@philadams In git-stats `2.0.0` the remotes will be kept in another way. Since the commit ids are unique, the can be stored in one object. And that makes the life easier.

**Comment by philadams** [comment]
Nice - anticipating your future work with excitement. Love this project - thank you!

**Comment by IonicaBizau** [comment]
Thank you, @philadams, for nice words! :smile: 

[`git-stats 2.0.0`](https://github.com/IonicaBizau/git-stats/pull/47) is almost here. :sparkles: 

See https://github.com/IonicaBizau/git-stats-importer/pull/26 for more information.
