### ISSUE TITLE
Import all my commits from all my repos

### ISSUE THREAD

**Issue by henvic** [IonicaBizau/git-stats-importer#10]
Add option to make git-stats-importer visit all the repos on my machine / working path, so I can automatically import everything.

e.g.,
`git-stats-importer --find-repos ~/projects`

**Comment by IonicaBizau** [comment]
That would be cool! :+1:

**Comment by as0n** [comment]
This should be easy using something like : 
`tree -adfi ~/path | grep -E ".git$"`

I'll probably give it a try. ;)

**Comment by IonicaBizau** [comment]
That's nice, but we should make it with native NodeJS tools.

**Comment by NoahBuscher** [comment]
I just did...

```
for d in ~/Documents/GitHub/*
do
   cd $d; git-stats-importer
done
```

Not the cleanest solution, but it'll do it. :tada:

**Comment by as0n** [comment]
@IonicaBizau : oh yeah you're right.

I can't help but think this feature should be merged in some way with the one from pull request #13 : they're both looking for git directories to import, one searches sub-directories (this issue) and the other searches parent directories (pull #13).

For example we could have a `path` optional argument (which would defaults to `./`) like so : 
```shell
$ git-stats ~/path
```
this would : 

1. Search *parent* directories for a git repo (as per pull request #13).
  1. If it finds one : import it and exit.
2. Search *sub*-directories for git repos (as per this issue)
  1. Display the list of found repos and ask user for a confirmation (we could use a `-a/--all` flag to force import)

This would avoid creating multiple options with similar behaviour. What do you think ?

**Comment by IonicaBizau** [comment]
Probably here, @daaku's [`walker` module](https://github.com/daaku/nodejs-walker) would be awesome. I haven't tried it yet, but it looks like it's what we need.

**Comment by jomo** [comment]
This is what I used:
```shell
find . -name .git -type d -print0 | xargs -0 -n1 dirname | sort --unique
```
Searches recursively for `.git` directories and then prints their parent dir.

**Comment by IonicaBizau** [comment]
This will be possible using [`git-repos`](https://github.com/IonicaBizau/node-git-repos). :sparkle: I'm on it.

**Comment by IonicaBizau** [comment]
I implemented this in #26. :star2:

**Comment by henvic** [comment]
Nice!

**Comment by IonicaBizau** [comment]
@henvic Thanks for tweets! :smile:
