### ISSUE TITLE
allow custom git log query for git log and items imported

### ISSUE THREAD

**Issue by ainthek** [IonicaBizau/git-stats-importer#17]
see my bash variant for this, I just need pass params to git log in JS.....

#!/bin/bash

	## Script to import selected git logs into git-stats
	##
	## Setup (prereq):
	##    npm install -g git-stats
	##    npm install -g git-stats-importer
	## 
	## Samples:   
	##    # cd some_repo
	##    git-stats-importer --delete
	##    
	##    git-stats-importer-custom --grep="\[FIX\]" --author=marcus --since="90 days ago"
	##    git stats
	##
	##    git-stats-importer --delete
	##    git-stats-importer-custom --grep="\[CODEREVIEW\]"
	##    git stats
	    
	if [ "$1" == "-h" -o  "$1" == "--help" -o $# == 0 ]
	then 
		. _usage.sh "${BASH_SOURCE[0]}" 2 --strip_hashes 1; exit 1;
		exit 1
	fi

	url=$(git config --get remote.origin.url)

	git log --format=$'%h\t%cd' "$@" |\
	while read c
	do
		IFS=$'\t' read -a parts <<< "$c"
		json='{"hash":"'${parts[0]}'", "date":"'${parts[1]}'", "url":"'$url'"}'
		git-stats --record "$json"
		echo $json
		#echo "imported ${parts[0]}, ${parts[1]}, $url"
	done

**Comment by IonicaBizau** [comment]
Nice! Can you add this in the readme file via a pull request?

**Comment by ainthek** [comment]
Feel free to do it by your self, quite bussy now....

**Comment by ainthek** [comment]
I have included that as port of the bin, so users can run it directly, see pull request please
