### ISSUE TITLE
allow custom .git-stats path as arg

### ISSUE THREAD

**Issue by Flyingmana** [IonicaBizau/git-stats-importer#2]
for the case I want this stats only for specific projects, it would be cool if I can point to a different file via an argument.

reference: https://github.com/IonicaBizau/git-stats/issues/8

**Comment by IonicaBizau** [comment]
:ship: `2.0.0` :tada:

**Comment by dogmatic69** [comment]
How is this used? Seems like `GitStats` is initialised with no argument so uses the default path.
