### ISSUE TITLE
.git-stats file empty after import

### ISSUE THREAD

**Issue by sime** [IonicaBizau/git-stats-importer#21]
Hello,

I have attempted to import a Git project, but `git-stats` doesn't work after importing.

Looking at the contents of `~/.git-stats` it only contains `{}`

**Comment by IonicaBizau** [comment]
Did you get any errors?

Also, check if the email set in your git config is the same with the one from commits you think are supposed to be imported.

**Comment by sime** [comment]
No errors:
```bash
$ git-stats-importer
info  Done.
```
E-Mails in `git log` match that of `git config user.email`

**Comment by IonicaBizau** [comment]
@sime Can you post the output of the following command:

```sh
git rev-list HEAD --author=`git config user.email` --count
```

Also, specify what operating system are you using.

**Comment by sime** [comment]
Solved.

My E-Mail address in `.gitconfig` was surrounded with single quotes.

Thanks!

**Comment by IonicaBizau** [comment]
Glad to hear the issue is solved. :smile: :+1:
