### ISSUE TITLE
Use parent-search

### ISSUE THREAD

**Issue by IonicaBizau** [IonicaBizau/git-stats-importer#24]
@as0n Maybe you can try to integrate [`parent-search`](https://github.com/IonicaBizau/node-parent-search) to replace [these lines](https://github.com/IonicaBizau/git-stats-importer/blob/9e047bf676410f502ebee0f278c7dd2f584fe3a2/bin/git-stats-importer#L19-L30).

**Comment by as0n** [comment]
@IonicaBizau Great !

I don't have much free time at the moment but I'll try to find some to implement this. No promises though. :/
