### ISSUE TITLE
TypeError: Object #<Object> has no method 'parse'

### ISSUE THREAD

**Issue by bdbogjoe** [IonicaBizau/git-stats-importer#27]
version 2.0.0

While trying to imports commits : 
```
/home/{user}/node_modules/git-stats-importer/node_modules/parent-search/lib/index.js:73
      , root = Path.parse(path).root
                    ^
TypeError: Object #<Object> has no method 'parse'
    at ParentSearch (/home/eric/node_modules/git-stats-importer/node_modules/parent-search/lib/index.js:73:21)
    at GitStatsImporter (/home/{user}/node_modules/git-stats-importer/lib/index.js:218:9)
    at Object.<anonymous> (/home/{user}/node_modules/git-stats-importer/bin/git-stats-importer:51:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

**Comment by bdbogjoe** [comment]
if you need any other details, please ask

**Comment by IonicaBizau** [comment]
Hmm, looks like the parse method is not available. Could you please tell me the output of `node --version` and what OS are you using?

**Comment by bdbogjoe** [comment]
OS : Linux 4.1.6-201.fc22.x86_64 #1 SMP Fri Sep 4 17:49:24 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

node --version : v0.10.36

**Comment by IonicaBizau** [comment]
Yes, I reproduced the error, but you really need to upgrade to a newer version of Node. I'm using [`nvm`](https://github.com/creationix/nvm) to switch between Node versions. For example, to reproduce this issue I did:

```sh
ionicabizau@notebook:~$ nvm install v0.10.36
######################################################################## 100,0%
Now using node v0.10.36 (npm v1.4.28)
ionicabizau@notebook:~$ node
> require("path")
{ resolve: [Function],
  normalize: [Function],
  join: [Function],
  relative: [Function],
  sep: '/',
  delimiter: ':',
  dirname: [Function],
  basename: [Function],
  extname: [Function],
  exists: [Function: deprecated],
  existsSync: [Function: deprecated],
  _makeLong: [Function] }
> require("path").parse
undefined
```

In your case, you should upgrade to a newer version (I recommend `4.0.0`). [Install `nvm`](https://github.com/creationix/nvm#install-script), and then do:

```sh
nvm install v4.0.0
nvm alias default v4.0.0
```

You can do the same with `v0.12.4` if you don't want to install `v4.0.0` which may break some modules (which are not updated to work with it yet). In fact, the `parse` method is not available in `v0.10.36` as you saw. :dizzy:

**Comment by bdbogjoe** [comment]
thanks, i installed node.js from yum/dnf, and seems version is outdated
I setup nvm and everthing is ok now, thanks

**Comment by IonicaBizau** [comment]
Glad to hear! You're very welcome! :+1: :smile:
